name: LeetCode Sync

on:
  schedule:
    - cron: "0 */2 * * *"  # Runs automatically every 2 hours
  workflow_dispatch:        # Allows manual trigger anytime

permissions:
  contents: write

jobs:
  leetcode-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync LeetCode Solutions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: leetcode-solutions
          commit-header: "LeetCode Sync - "
